# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import bone_pb2 as bone__pb2


class MLStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Morph = channel.unary_unary(
        '/bone.ML/Morph',
        request_serializer=bone__pb2.Frame.SerializeToString,
        response_deserializer=bone__pb2.Image.FromString,
        )


class MLServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Morph(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MLServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Morph': grpc.unary_unary_rpc_method_handler(
          servicer.Morph,
          request_deserializer=bone__pb2.Frame.FromString,
          response_serializer=bone__pb2.Image.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'bone.ML', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
